version: '2'

services:
  backend:
    build: backend
    command: sh -c './wait-for.sh db:5432 -- npm run dev' 
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - 9000:9000
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://dev_user:devUs3r@db/dev_db

  frontend:
    build: frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 8000:8000
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - ENDPOINT=http://localhost:9000
  db:
    build: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=devUs3r
      - POSTGRES_DB=dev_db
    ports:
      - 5432:5432

volumes:
  dbdata:       
